  - uri:
      url: "https://discovery.etcd.io/new?size=3"
      return_content: yes
    register: infra_etcd2_discovery_url

  - name: Create master nodes
    local_action:
      module: cs_instance
      name: "{{ cluster_name }}-master-{{ item }}"
      template: "Linux CoreOS stable 1122 64-bit 10G Disk (2016-09-06-dcb493)"
      service_offering: "{{ master_instance_size }}"
      ssh_key: "{{ ssh_key }}"
      security_groups: [ '{{ master_security_group_name }}' ]
      user_data: "{{ lookup('template', '../templates/master_user_data.j2') }}"
      zone: "{{ cluster_zone }}"
    with_sequence: count=3
    register: created_master_nodes

  - add_host:
      groups: master_nodes
      hostname: "{{ item.display_name }}"
      ansible_host: "{{ item.default_ip }}"
      ansible_user: core
      ansible_ssh_private_key_file: "~/.ssh/id_rsa_{{ ssh_key }}"
      ansible_python_interpreter: /home/core/bin/python
    with_items: "{{ created_master_nodes.results }}"
