- name: Create SSH Key
  local_action:
    module: cs_sshkeypair
    name: "{{ ssh_key }}"
  register: key
  tags: sshkey

- local_action: copy content="{{ key.private_key }}" dest="../secret/id_rsa_{{ ssh_key }}"
  when: key.changed
  tags: sshkey

- file: path="../secret/id_rsa_{{ ssh_key }}" mode=0600
  when: key.changed
  tags: sshkey
